# MLFlow is hidden behind nginx, allowing user auth to be implemented.

version: '1.0'

services:
    app:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - ${MLFLOW_PORT}
        networks:
            - frontend
            - backend
        volumes:
           - type: bind
             source: ./mlruns
             target: /mlruns
        environment:
            - BACKEND=./mlruns
            - ARTIFACTS=./mlruns
        command: 
            - sh
            - -c
            - mlflow server 
                --port ${MLFLOW_PORT}
                --host 0.0.0.0 
                --backend-store-uri file:$${BACKEND}
                --default-artifact-root file:$${ARTIFACTS}


    nginx:
        restart: always
        build: 
            context: ./nginx
            args:
              - NGINX_HTTP_AUTH_USER=${NGINX_HTTP_AUTH_USER} 
              - NGINX_HTTP_AUTH_PASSWORD=${NGINX_HTTP_AUTH_PASSWORD}
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "${MLFLOW_PORT}:80"
        networks:
            - frontend
        depends_on:
            - app

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
